name: Update Browserslist DB
on:
  workflow_call:
    secrets:
      requirements_bot_github_token:
        required: true

jobs:
  update-dep:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install Dependencies
      run: npm ci

    - name: Update browserslist DB
      run: npx update-browserslist-db@latest

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
          token: ${{ secrets.requirements_bot_github_token }}
          commit-message: 'chore: update browserslist DB'
          title: Update browserslist DB
          body: |
            Updated browserslist DB
          branch: update-browserslist-db

    - name: Auto-Approve the Pull Request
      uses: hmarr/auto-approve-action@v3
      with:
        github-token: ${{ secrets.requirements_bot_github_token }}
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}

    - name: Enable Pull Request Automerge
      run: gh pr merge --merge --auto "${{ steps.cpr.outputs.pull-request-number }}"
      env:
        GITHUB_TOKEN: ${{ secrets.requirements_bot_github_token }}
